adding composer

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -30,8 +30,21 @@ jobs:
          command: git --version
       - run:
          name: install composer
-         command: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
-
+         command: |
+             cd /tmp
+             EXPECTED_SIGNATURE=$(curl -q https://composer.github.io/installer.sig)
+             php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+             ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+             if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+             then
+                 >&2 echo 'ERROR: Invalid installer signature'
+                 rm composer-setup.php
+                 exit 1
+             fi
+             sudo php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
+             RESULT=$?
+             rm composer-setup.php
+             exit $RESULT
       - run:
          name: composer install
          command: composer install
